.github/workflows/deploy.yml, server/api-server/Dockerfile
- close #5
- Github Action과 Docker로 CI/CD를 구축했습니다.
=> [chore] API 서버 CI/CD

.github/workflows/deploy.yml, server/api-server/yarn.lock, server/encoding-server/.gitignore, server/encoding-server/Dockerfile, server/encoding-server/app.js, server/encoding-server/package-lock.json, server/encoding-server/package.json, server/rtmp-server/.gitignore, server/rtmp-server/Dockerfile, server/rtmp-server/app.js, server/rtmp-server/package-lock.json, server/rtmp-server/package.json
- Resolves #8
- node-media-server 라이브러리 적용
- 스트리밍 송신, 인코딩 수신 테스트
- 스트리밍/인코딩 서버 CI/CD 추가
=> [feat] 스트리밍/인코딩 서버 세팅 및 송수신 구현

.github/workflows/deploy.yml, server/encoding-server/Dockerfile, server/rtmp-server/Dockerfile
- Resolves #13
- CI/CD의 잘못돼있던 부분들을 수정했습니다.
=> [fix] CI/CD 수정

client/tsconfig.json, client/vite.config.ts
- Close #26 프론트엔드 절대경로 설정
- 프론트엔드 절대경로 설정
=> [chore] 프론트엔드 절대경로 설정

.github/workflows/deploy.yml, server/api-server/package-lock.json, server/api-server/package.json, server/api-server/sql/schema.sql, server/api-server/src/app.module.ts, server/api-server/src/streams/dto/create-stream.dto.ts, server/api-server/src/streams/dto/update-stream.dto.ts, server/api-server/src/streams/entities/stream.entity.ts, server/api-server/src/streams/streams.controller.spec.ts, server/api-server/src/streams/streams.controller.ts, server/api-server/src/streams/streams.module.ts, server/api-server/src/streams/streams.service.spec.ts, server/api-server/src/streams/streams.service.ts, server/api-server/src/users/dto/create-user.dto.ts, server/api-server/src/users/dto/update-user.dto.ts, server/api-server/src/users/entities/user.entity.ts, server/api-server/src/users/users.controller.spec.ts, server/api-server/src/users/users.controller.ts, server/api-server/src/users/users.module.ts, server/api-server/src/users/users.service.spec.ts, server/api-server/src/users/users.service.ts, server/api-server/yarn.lock
- Resolves #54 
- TypeORM 연관관계 매핑
- 임시 CRUD 코드 생성
- schema.sql 작성
- deploy.yml API 서버 환경 변수 추가
도커로 `mysql` 실행
```
docker run -e MYSQL_ROOT_PASSWORD=123 -p 3306:3306 -d mysql
```
`mysql`에 `gbs` 데이터베이스 생성
```sql
mysql> CREATE DATABASE gbs;
```
`api-server` 폴더에 `.env` 파일 추가
```
DB_HOST=localhost
DB_PORT=3306
DB_ID=root
DB_PW=123
DB_NAME=gbs
```
=> [feat] TypeORM 연관관계 매핑

README.md
- Resolves #58 README.MD 보완하기
- README.md 설명 추가
=> [docs] README.md 보완하기

client/src/pages/BroadcastPage/BroadcastPage.tsx
- close #65 
- 엔터키로 채팅 보내는 기능 구현
- 엔터와 쉬프트키로 줄을 바꿔주는 기능 구현
=> [feat] 엔터키로 채팅 보내는 기능 구현

.github/workflows/deploy.yml, server/api-server/Dockerfile, server/rtmp-server/Dockerfile, server/rtmp-server/nginx.conf
- Resolves #61
- [arut/nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module) 에서 [winshining/nginx-http-flv-module](https://github.com/winshining/nginx-http-flv-module) 로 변경
- 기존 모듈을 fork해 기능을 추가한 모듈
- 기존 모듈은 JSON으로 동영상 정보를 조회하는 기능이 없다.
- Github Actions context 추가
- 로컬과 경로를 통일하기 위해
```json
{
"http-flv": {
"nginx_version": "1.25.4",
"nginx_http_flv_version": "1.2.11",
"compiler": "gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) ",
"built": "Nov 21 2023 13:37:21",
"pid": 8,
"uptime": 20,
"naccepted": 0,
"bw_in": 0,
"bytes_in": 0,
"bw_out": 0,
"bytes_out": 0,
"servers": [
{
"port": 1935,
"server_index": 0,
"applications": [
{
"name": "live",
"live": {
"streams": [],
"nclients": 0
},
"recorders": {
"count": 0,
"lists": []
}
}
]
}
]
}
}
```
```json
{
"http-flv": {
"nginx_version": "1.25.4", …
```
=> [feat] 스트리밍 서버 - 동영상 정보 조회 기능 추가

client/src/App.tsx, client/src/components/Broadcast/Broadcast.styles.tsx, client/src/components/ThemeSwitch/ThemeSwitch.styles.tsx, client/src/components/ThemeSwitch/ThemeSwitch.tsx, client/src/main.tsx, client/src/pages/MainPage/MainPage.tsx, client/src/state/theme.ts, client/src/styles/GlobalStyles.styles.tsx, client/src/styles/theme.ts
- Resolves #64
- 전역상태를 이용한 다크모드/라이트모드 변환
- 로고 색 변경 
- border 색 변경
https://github.com/boostcampwm2023/web07-GBS/assets/21211957/5287baae-ce42-44b3-b796-a45e40524b42
=> [feat] 다크모드 만들기

server/api-server/src/common/dto/page.dto.ts, server/api-server/src/streams/dto/create-stream.dto.ts, server/api-server/src/streams/dto/read-stream-detail.dto.ts, server/api-server/src/streams/dto/read-stream.dto.ts, server/api-server/src/streams/dto/update-stream.dto.ts, server/api-server/src/streams/dto/video-info.dto.ts, server/api-server/src/streams/entities/stream.entity.ts, server/api-server/src/streams/provider/video-info.provider.ts, server/api-server/src/streams/streams.controller.ts, server/api-server/src/streams/streams.module.ts, server/api-server/src/streams/streams.service.ts, server/api-server/src/users/entities/user.entity.ts, server/api-server/src/users/users.module.ts
- Resolves #44
- 방송 정보 CRUD API 구현
- GET /streams
- GET /streams/:userId
- PATCH /streams/:userId
- TODO
- 테스트 코드 구현
- viewer, thumbnail 구현
- Validation 구현
- Stream 생성은 회원가입 할 때 같이 하면 좋을 것 같아요.
=> [feat] 방송 정보 CRUD API 구현

client/src/components/Modal/LoginModal/LoginModal.stories.tsx, client/src/components/Modal/LoginModal/LoginModal.styles.tsx, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/RegisterModal/Register.stories.tsx, client/src/components/Modal/RegisterModal/RegisterModal.styles.tsx, client/src/components/Modal/RegisterModal/RegisterModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx
- Resolves #82 
- 다크모드 변경 시 채팅창 배경색 변경
=> [fix] 다크모드 변경 시 채팅창 배경색 변경

server/api-server/Dockerfile, server/api-server/package.json, server/api-server/src/auth/auth.controller.ts, server/api-server/src/auth/auth.service.ts, server/api-server/src/auth/strategy/naver.strategy.ts, server/api-server/src/init.session.ts, server/api-server/src/streams/streams.module.ts, server/api-server/src/users/dto/update-user.dto.ts, server/api-server/src/users/entities/user.entity.ts, server/api-server/src/users/users.controller.ts, server/api-server/src/users/users.module.ts, server/api-server/src/users/users.service.ts, server/api-server/yarn.lock
- Resolves #77 
- redis 연결오류 해결
- 서버 로그인 확인 완료
- nickname 변경 API 구현 완료
로그인
GET /oauth/login/naver
nickname 변경
cookie에 있는 sessionId로 session에서 userId 가져옴
PATCH users
{
nickname: "dummy"
}
=> [fix] redis 연결, 로그인&회원가입완료

client/.gitignore, client/src/hooks/useApi.ts
- Resolves #89
- api를 불러오고 loading과 error 상태를 쉽게 관리할 수 있는 커스텀 훅 제작
=> [feat] useApi 커스텀 훅 제작

client/src/pages/BroadcastPage/BroadcastPage.tsx, server/api-server/package.json, server/api-server/src/chat/chat.gateway.spec.ts, server/api-server/src/chat/chat.gateway.ts, server/api-server/src/chat/chat.module.ts, server/api-server/src/chat/dto/chat-payload.ts, server/api-server/src/init.session.ts, server/api-server/src/main.ts, server/api-server/src/redis.adapter.ts, server/api-server/src/redis.session.ts, server/api-server/src/streams/streams.module.ts, server/api-server/src/streams/streams.service.ts, server/api-server/src/users/users.controller.ts, server/api-server/src/users/users.service.ts, server/api-server/yarn.lock
- Resolves #92
- 채팅 서버 Redis Pub/Sub 연결
- RedisIoAdapter 구현
- 세션 적용
- 로깅 추가
=> [feat] 채팅 서버 Redis Pub/Sub 연결

.github/workflows/deploy.yml
- Resolves #102
- https 연결을 위해서 인증서 발급 후, docker run 후에 인증서 추가
=> [feat] : https 연결을 위한 deploy.yml 변경

.github/workflows/deploy.yml
- Resolves #108
- 443포트 오픈안해서 오류났던 부분 해결
- docker run 할 때 443 포트 오픈
=> [fix] https 연결을 위한 443 port 오픈

.github/workflows/deploy.yml, client/.eslintrc.cjs, client/src/components/Modal/SettingModal/SettingModal.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx
- closes #105 
- refactor : location.state로 id를 받을 수 있도록 개선
- refactor : socket을 useRef를 사용해 호출하도록 개선
- design : 환경설정모달 디자인 수정
- fix : deploy.yml 수정
=> [refactor] Socket을 여러 번 불러오는 오류 수정

.github/workflows/deploy-front.yml, client/Dockerfile, docker-compose.yml, server/rtmp-server/Dockerfile
- Resolves #99
- docker-compose로 로컬 테스트 환경 구축
=> [feat] docker-compose 로컬 테스트 환경 구축

client/src/pages/BroadcastPage/BroadcastPage.tsx, server/api-server/src/auth/strategy/naver.strategy.ts, server/api-server/src/chat/chat.gateway.ts, server/api-server/src/main.ts
=> [fix] HTTPS 적용 후 채팅 안되는 문제 해결

server/api-server/src/auth/strategy/naver.strategy.ts, server/api-server/src/main.ts, server/api-server/src/streams/stream-keys.controller.ts, server/api-server/src/streams/streams.controller.ts, server/api-server/src/streams/streams.service.ts, server/api-server/src/users/users.controller.ts, server/api-server/src/users/users.service.ts
- Resolves #127 
- streamkey 반환
- login 후 session에 user.userId 반환하도록 수정
=> [feat] streamkey 반환

docker-compose.yml, server/api-server/package.json, server/api-server/src/chat/chat.gateway.ts, server/api-server/src/main.ts
- close #133 
- WebSocket 에러 반환 시 서버 꺼지는 문제 해결
- try-catch 후 에러 로깅
- 로컬 테스트 환경 개선
=> [fix] WebSocket 에러 반환 시 서버 꺼지는 문제 해결

client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx
- Resolves #123 
- 새로고침 시 404 해결 (인프라 nginx 설정 문제)
- url로 접속 시 방송 접속 안되는 문제 해결
- 방송정보 api로 가져오게 변경
=> [fix] 새로고침 시 404 해결 & 메인 화면 방송 리스트 api 연결

client/src/pages/BroadcastPage/BroadcastPage.tsx
- Resolves #137 
- pr이 꼬여서 빌드오류 났던 부분 해결
=> [feat] : 프론트 컨플릭트 이슈 해결

server/api-server/.eslintrc.js, server/api-server/src/main.ts, server/api-server/src/streams/streams.service.ts
- close #139 
- 방송 목록/단건 조회 StreamKey 감추기
- NODE_ENV 오타 수정
=> [fix] StreamKey 감추기, 오타 수정

client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/SettingModal/SettingModal.styles.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, server/api-server/src/main.ts
- close #131 
- ID 및 닉네임 수정 기능 구현
- 로그인 했을 때만 ID 및 닉네임 수정 가능하게 구현
- 방송 비밀키 클립보드에 복사하는 기능 구현
=> [feat] 환경 설정에서 ID 및 닉네임 수정 & 스트리밍 비밀 키 복사 기능 구현

client/Dockerfile, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/hooks/useApi.ts
- Resolves #142
- fetch -> useApi로 변경
- url 관련 환경변수 추가
=> [fix] useApi 변경 및 환경변수 추가

.github/workflows/deploy-front.yml
=> [fix] 환경변수 수정

client/src/components/Broadcast/Broadcast.styles.tsx, client/src/components/Broadcast/Broadcast.tsx, client/src/components/Chatting/Chatting.styles.tsx, client/src/components/Chatting/Chatting.tsx, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx
- close #156 
- 방송 제목 기본값 설정
- 말줄임표 적용
- 정렬이 안되는 오류 수정
- 시청자 수에 콤마를 붙여주는 기능 구현
=> [fix] 방송 제목 예외처리 및 말줄임표 적용

.github/workflows/deploy-front.yml, client/Dockerfile, client/src/components/HlsPlayer/HlsPlayer.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx
- Resolves #157 
- HlsPlayer 컴포넌트를 Boradcast 화면에 연결
- VITE_HLS_URL 환경변수 추가 및 배포 시 dockerfile과 yml에 추가
=> [feat] HlsPlayer를 사용해 방송화면에 실시간 스트리밍 화면 연결

client/src/components/HlsPlayer/HlsPlayer.tsx
- Resolves #163
- hls 통신 시 m3u8 확장자 누락 해결
=> [fix] m3u8 확장자 누락 해결

client/Dockerfile, client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx
- close #161 
- 방송 목록이나 정보 조회 실패시 모달창을 띄우고 새로고침 하는 기능 구현
- 모달창의 가로 너비 변경
=> [feat] 방송 목록이나 정보 조회 실패시 모달창을 띄우고 새로고침 하는 기능 구현

client/src/pages/MainPage/MainPage.tsx
- close #166 
- 방송 제목을 제대로 못가져오는 오류 수정
=> [fix] 방송 제목을 제대로 못가져오는 오류 수정

server/api-server/src/auth/auth.module.ts
- Resolves #173 
- AuthModule에 누락된 GoogleStrategy 추가
=> [fix] AuthModule에 누락된 GoogleStrategy 추가

client/src/components/Modal/LoginModal/LoginModal.tsx
=> [feat] 클라이언트 - 구글 로그인 구현

server/api-server/src/auth/strategy/google.strategy.ts, server/api-server/src/chat/chat.gateway.ts
=> [fix] chatting 이름 표기 오류 해결

client/src/components/Chatting/Chatting.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx
- close #186 
- 채팅 리스트 가로 길이 수정
- 강퇴 오류 수정
=> [fix] 강퇴가 안되는 오류 수정

client/src/components/Access/Access.tsx, client/src/components/Chatting/Chatting.styles.tsx, client/src/components/Modal/SettingModal/SettingModal.styles.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.styles.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/states/filter.ts, client/src/states/user.ts, client/src/types/user.ts, server/api-server/src/chat/chat.gateway.ts, server/api-server/src/chat/dto/chat-payload.dto.ts
- close #193 
- 필터를 껐다 켰다 하는 기능 구현
=> [feat] AI 필터를 껐다 켰다 하는 기능 구현

README.md, client/src/components/Modal/SettingModal/SettingModal.tsx
- close #197 
- 환경 설정 모달창 디자인 변경
=> [design] 환경 설정 모달창 디자인 변경

server/api-server/src/thumbnails/thumbnails.service.ts
- S3 Thumbnail 유효기간 설정, prefix 설정으로 url 변경
=> [fix] thumbnail url 수정

server/api-server/src/thumbnails/thumbnails.service.ts, server/encoding-server/nginx.conf
- S3 Thumbnail 유효기간 설정, prefix 설정으로 url 변경
=> [fix] thumbnail url 변경

client/src/components/Modal/ConfirmModal/ConfirmModal.styles.tsx, client/src/components/Modal/ConfirmModal/ConfirmModal.tsx, client/src/components/Modal/LoginModal/LoginModal.styles.tsx, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/SettingModal/SettingModal.styles.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/components/Modal/ViewerModal/ViewerModal.styles.tsx, client/src/components/Modal/ViewerModal/ViewerModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx, client/src/types/modal.ts
- close #207 
- 모달창 애니메이션 추가
- 채팅 길이제한 기능 구현
=> [feat] 모달창 애니메이션 추가

client/src/components/Modal/ConfirmModal/ConfirmModal.stories.tsx
- close #211 
- Storybook 오류 수정
=> [fix] Storybook 오류 수정

client/src/components/HlsPlayer/HlsPlayer.tsx, client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx, client/src/states/filter.ts, client/src/states/theme.ts
- close #213 
- 채팅을 보내면 초점을 잃는 기능 추가
- 코드에 있는 console.log 제거
- 닉네임 변경 후 채팅을 치지 못하는 오류 수정
- 채팅 필터링 기본값 false로 수정
- 다크모드 관련 코드 리팩토링
=> [feat] 채팅을 보내면 초점을 잃는 기능 추가

client/src/pages/BroadcastPage/BroadcastPage.tsx
- close #215 
- 채팅을 치고 나면 포커스를 잃는 오류 수정
=> [fix] 채팅을 치고 나면 포커스를 잃는 오류 수정

client/src/components/Modal/SettingModal/SettingModal.tsx, client/src/pages/BroadcastPage/BroadcastPage.tsx, client/src/pages/MainPage/MainPage.tsx, server/api-server/src/streams/streams.service.ts
- close #217 
- 방송 중에 ID 및 닉네임을 바꿀 수 없도록 수정
=> [fix] 방송 중에 ID 및 닉네임을 바꿀 수 없도록 수정

client/src/pages/BroadcastPage/BroadcastPage.tsx
=> [fix] 채팅 오류 수정

client/src/pages/BroadcastPage/BroadcastPage.tsx
- close #221 
- 모달창이 띄워져도 채팅이 입력되는 오류 수정
=> [fix] 모달창이 띄워져도 채팅이 입력되는 오류 수정

client/src/pages/BroadcastPage/BroadcastPage.tsx
- close #221 
- 모달창이 떠있어도 엔터키가 입력되는 오류 수정
=> [fix] 모달창이 떠있어도 엔터키가 입력되는 오류 수정

server/api-server/src/users/users.controller.ts
=> [fix] user controller 수정

client/src/components/Access/Access.tsx, client/src/components/Chatting/Chatting.tsx, client/src/components/HlsPlayer/HlsPlayer.tsx, client/src/components/Logo/Logo.tsx, client/src/components/Modal/LoginModal/LoginModal.tsx, client/src/components/Modal/ViewerModal/ViewerModal.tsx
- Resolves #228 
- 스토리북 설명 수정.
=> [fix] 스토리북 설명 수정

README.md, client/src/pages/MainPage/MainPage.styles.tsx
- close #230 
- 노션 링크 수정
- 메인 화면에서 가로 스크롤이 생기지 않도록 수
=> [docs] README.md 노션 링크 변경

README.md
- close #235 
- README.md 파일 수정
=> [docs] README.md 파일 수정
